fix analysis results

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,10 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+echo "Checking project health..."
+flutter analyze || {
+  echo "❌ Static analysis failed. Please fix the issues before committing."
+  exit 1
+}
+
 dart run lint_staged
